// Mocks generated by Mockito 5.2.0 from annotations
// in image_search/test/repositories/org_api_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:image_search/core/resources/result.dart' as _i2;
import 'package:image_search/data/data_sources/org_api.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeResult_0<T> extends _i1.Fake implements _i2.Result<T> {}

/// A class which mocks [OrgApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrgApi extends _i1.Mock implements _i3.OrgApi {
  MockOrgApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: '',
      ) as String);
  @override
  _i4.Future<_i2.Result<Iterable<dynamic>>> fetch() => (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [],
        ),
        returnValue: Future<_i2.Result<Iterable<dynamic>>>.value(
            _FakeResult_0<Iterable<dynamic>>()),
      ) as _i4.Future<_i2.Result<Iterable<dynamic>>>);
}
